name: Deploy to NAS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.NAS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 192.168.100.198 >> ~/.ssh/known_hosts

    - name: Deploy to NAS
      run: |
        ssh -i ~/.ssh/id_ed25519 ericerwin@192.168.100.198 << 'EOF'
          cd /volume1/docker/wordpress-cloud-project
          git pull origin main
          docker compose pull
          docker compose up -d --remove-orphans
        EOF
