name: WordPress CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build containers
        run: docker compose build

      - name: Run unit tests (placeholder)
        run: echo "No tests yet"

      - name: Deploy (placeholder)
        run: echo "Deploy to staging or production"
