name: Deploy to NAS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NAS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan your-nas-ip >> ~/.ssh/known_hosts

      - name: Deploy to NAS
        run: |
          ssh eric@your-nas-ip <<EOF
            cd /volume1/docker/wordpress-cloud-project
            git pull
            docker compose up -d --build
          EOF
